#database
MONGO_URL = "mongodb://localhost:27017/"
MONGO_DB_NAME = "QuizTime"

#redis
REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_DB = 0

#bot
BOT_TOKEN = "8096422846:AAFO58-yqffRoqdyQj5iWi684QARI5Y1rUg"
BOT_USER_ID = 8096422846
BOT_USERNAME = "@ProfessorquizBot"
BOT_NAME = "UPSSSC ALERT QUIZ BOT"


#sponsor
SPONSOR_CHANNEL_ID = --1001810324762
SPONSOR_CHANNEL_NAME = "UPSSSC ALERT"
SPONSOR_CHANNEL_URL = "https://t.me/upssscalert"



#admin
ADMIN_ID = 833340583

# تغییر ADMIN_ID به ADMIN_IDS به صورت لیست
ADMIN_IDS = ["833340583"]

#Topic Settings
TOPIC_NAME_MAX_LENGTH = 20
TOPIC_NAME_MIN_LENGTH = 3
TOPIC_DESCRIPTION_MAX_LENGTH = 200
TOPIC_DESCRIPTION_MIN_LENGTH = 20

#Question Settings
QUESTION_MAX_LENGTH = 50
QUESTION_MIN_LENGTH = 10

OPTION_MAX_LENGTH = 20
OPTION_MIN_LENGTH = 1
OPTION_COUNT = 4

#Quiz Settings
QUIZ_COUNT_OF_QUESTIONS_LIST = [7, 10, 14]
QUIZ_COUNT_OF_QUESTIONS = QUIZ_COUNT_OF_QUESTIONS_LIST[0]
QUIZ_TIME_LIMIT_LIST = [10, 13, 16]
QUIZ_TIME_LIMIT = QUIZ_TIME_LIMIT_LIST[0]


# Main menu buttons
MAIN_MENU_START_QUIZ_BUTTON = "🎮 کوییز"
MAIN_MENU_LEADERBOARD_BUTTON = "📊 آمار من"
MAIN_MENU_GLOBAL_LEADERBOARD_BUTTON = "🏆 رتبه‌بندی"
MAIN_MENU_HELP_BUTTON = "🔍 راهنما"
MAIN_MENU_SUBMIT_QUESTION_BUTTON = "🎯 ارسال سوال جدید"
